apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-kubetest-deployment
spec:
  selector:
    matchLabels:
      app: demo2
  replicas: 2
  template:
    metadata:
      labels:
        app: demo2
    spec:
      containers:
        - name: springboot-kubetest
          image: springboot-kubetest:1.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8084